# Input prompt audio recording (for local models it should be a .wav file using 16kHz sampling rate).
string recording_file
---
# Generated speech synthesis, if enabled.
string speech_file
# Generated text response.
string text_response
---
# Feedback with current state of the commander.
int8 state
